### ISSUE TITLE
stunnel failing to start in newly launched config-server

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#175]
I get the following error:
```
----------
          ID: stunnel4
    Function: service.running
      Result: False
     Comment: Service stunnel4 is already enabled, and is dead
     Started: 07:30:22.726293
    Duration: 107.73 ms
     Changes:   
----------
```
Since the config server depends on stunnel4 it won't start up.  I'm reverting stunnel4 and the dependency of config-server on it until it works.
